# Generated by Django 3.0.6 on 2020-05-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alcohol_percent', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Variety',
                'verbose_name_plural': 'Varieties',
            },
        ),
        migrations.CreateModel(
            name='VarietyFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=150)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreamapp.Flavor')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreamapp.Variety')),
            ],
        ),
        migrations.AddField(
            model_name='variety',
            name='flavors',
            field=models.ManyToManyField(through='icecreamapp.VarietyFlavor', to='icecreamapp.Flavor'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='varieties',
            field=models.ManyToManyField(through='icecreamapp.VarietyFlavor', to='icecreamapp.Variety'),
        ),
    ]
